### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jd-alexander** [newventuresoftware/WaveformControl#1]
It would be nice if we could get an image or demo of how this looks. Really interested in putting it in my project.

**Comment by yavor87** [comment]
Hey @jd-alexander, good point! I took a screenshot for [my blog](http://www.newventuresoftware.com/blog/record-play-and-visualize-raw-audio-data-in-android/), but didn't put it in the Readme here.

The demo is actually part of the project. You can find it in the [app](https://github.com/newventuresoftware/WaveformControl/tree/master/app) folder.

**Comment by jd-alexander** [comment]
Ok awesome!

**Comment by jd-alexander** [comment]
are you planning to add it to maven central or jitpack repo?

**Comment by yavor87** [comment]
Yeah, it makes sense.

**Comment by jd-alexander** [comment]
:+1:
