### ISSUE TITLE
Where's the part of recording ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [newventuresoftware/WaveformControl#11]
I can't see that it actually records anything...
To which file does it record? Where does it start and where does it stop recording?

**Comment by yavor87** [comment]
Hey @AndroidDeveloperLB !

The recording is done in the [RecordingThread](https://github.com/newventuresoftware/WaveformControl/blob/master/app/src/main/java/com/newventuresoftware/waveformdemo/RecordingThread.java) and the playback -> [PlaybackThread](https://github.com/newventuresoftware/WaveformControl/blob/master/app/src/main/java/com/newventuresoftware/waveformdemo/PlaybackThread.java) The sample app isn't recording actually, but rather collecting the samples from the microphone and creating a waveform to visualize them.

**Comment by AndroidDeveloperLB** [comment]
Don't I need to investigate hot to encode to a known file format this way? Even the simplest one (WAV) has its own specifications...

Anyway, I get it that this sample isn't about it, so I close it.

**Comment by yavor87** [comment]
The wave, as far as I know, is uncompressed. It only has a few bytes as header stating that this is a wave file and some other metadata, but the rest is just raw uncompressed data.

**Comment by AndroidDeveloperLB** [comment]
Can you please show how to do it, perhaps? 
Maybe using this library:
https://github.com/google/oboe/
?

**Comment by yavor87** [comment]
I have done it manually using guides like this one:
http://soundfile.sapp.org/doc/WaveFormat/ . I am not familiar with oboe and
I can't help you much with it.

**Comment by AndroidDeveloperLB** [comment]
OK thank you.
