### ISSUE TITLE
How to load "samples" from a sound file in the local file system?

### ISSUE THREAD

**Issue by liuzhen2008** [newventuresoftware/WaveformControl#4]
I try to use the `inputFileStream(new File(filePath))` directly on line https://github.com/newventuresoftware/WaveformControl/blob/master/app/src/main/java/com/newventuresoftware/waveformdemo/MainActivity.java#L125 and convert it to byte array. But the resulting image/play back doesn't seem to work properly.

I also used a plain mp3 file as resource. The result is almost a rectangle. Is there any preprocess that needs to be done to the file?

The sound file i am interesting in showing a graph for is created by a MediaRecorder with the following configuration:

        MediaRecorder recorder = new Mediarecorder();
        recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        recorder.setOutputFormat(MediaRecorder.OutputFormat.DEFAULT);
        recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);

**Comment by liuzhen2008** [comment]
Basically i need to convert this 3gp stuff to PCM samples using MediaExtractor/MediaCodec.

**Comment by yavor87** [comment]
I reckon it's because of the compression. Currently, the code works only with uncompressed data. The snippet that you shared sets the encoder to AMR (Narrowband) audio codec, which should produce some compression on the resulting stream.

**Comment by liuzhen2008** [comment]
@yavor87  Yes thats exactly it. I used mediaCodec to convert the 3gp audio samples into PCM audio  samples and the graph worked flawlessly.

**Comment by irshadshalu** [comment]
@liuzhen2008  Could you share your solution?

**Comment by liuzhen2008** [comment]
```

**Comment by irshadshalu** [comment]
Thank you!

**Comment by mgood7123** [comment]
so just to be clear, does this accept `.wav` files or `.raw` files as input for the waveform to render and/or play
