### ISSUE TITLE
Will it record android system audio output running on background along with user talking?

### ISSUE THREAD

**Issue by sulaimansust** [newventuresoftware/WaveformControl#6]
I have implemented AudioRecord which can record my voice but it force the media player to stop during the record. Will your program record background music playing at the device with users talking? If yes, how did you handled that?

**Comment by yavor87** [comment]
You want to record the music currently played by the device, right?

**Comment by sulaimansust** [comment]
Yes

**Comment by yavor87** [comment]
Can you share the resolution @sulaimansust ?

**Comment by sulaimansust** [comment]
Actually my problem is partially solved. I couldn't take the system audio output but i was able to take Background music + my voice via Audio Recorder and MediaRecorder in normal process. I have seen in android sdk api documentation that only system apps can system audio output. But in android NDK sample code on git , an app name audio-echo and native-audio says we can take system audio output that recently played on system audio output can be taken. As I am new in android ,i couldn't understand NDK codes. I am sharing you NDK links. https://github.com/googlesamples/android-ndk/tree/master/audio-echo
Read it's usage description.
